const URL = "http://localhost/api";
export const URL_IDEA = URL.concat("/idea");
export const URL_EMPLOYEE = URL.concat("/userEmployee");
export const URL_PROPOSAL = URL.concat("/productProposal");
export const URL_DESIGN = URL.concat("/design");
export const URL_CATEGORY = URL.concat("/categoryIdea");
export const URL_ROLE = URL.concat("/role");
export const URL_REVIEW_PROPOSAL = URL.concat("/reviewProductProposal");
export const URL_REVIEW_DESIGN = URL.concat("/reviewDesign");